### PR TITLE
Update recipe to nvcomp 4.1.0.6.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
@jakirkham It doesn't seem like Azure CI ran. Do you know how to debug this? I will try closing and reopening.

**Comment by bdice** [comment]
I looked at the Azure logs from the CI run on the first commit. I see an error on Windows.

```
The system cannot find the file specified.
%SRC_DIR%\\lib\\nvcomp*.dll 
```

I see a difference in Windows packaging and asked about it internally.

nvcomp 4.0.1:

```
~/Downloads/nvcomp-windows-x86_64-4.0.1-cuda12.x/nvcomp/lib $ ls
cmake  nvcomp.dll  nvcomp.lib  nvcomp_cpu.dll  nvcomp_cpu.lib  nvcomp_cpu_static.lib  nvcomp_device_static.lib  nvcomp_static.lib
```

nvcomp 4.1.0.6:

```
~/Downloads/nvcomp-windows-x86_64-4.1.0.6_cuda12-archive/lib $
cmake  nvcomp.lib  nvcomp_cpu.lib  nvcomp_cpu_static.lib  nvcomp_device_static.lib  nvcomp_static.lib
```

**Comment by bdice** [comment]
Still doesn't seem like Azure is launching CI... 😕

**Comment by bdice** [comment]
@conda-forge-admin please restart ci

**Comment by bdice** [comment]
@conda-forge-admin please rerender

**Comment by bdice** [comment]
@conda-forge-admin please restart co

**Comment by bdice** [comment]
@conda-forge-admin please restart ci

**Comment by bdice** [comment]
@conda-forge-admin please restart ci

**Comment by bdice** [comment]
https://github.com/conda-forge/status/issues/188 is marked as resolved but I'm still seeing issues. I'll try to rerun again...

**Comment by bdice** [comment]
@conda-forge-admin please restart ci

**Review by jakirkham — APPROVED** [review]
Thanks Bradley! 🙏

**Pull request merged**
