### PR TITLE
Update recipe to nvcomp 3.0.6.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

This needs a fix to the skip. Currently it is building for CUDA 11.2 & 11.8. However we only need one

Let's keep CUDA 11.8 and skip 11.2 as the latter is going away in the not too distant future

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Seeing this error in [the Linux ARM builds]( https://app.travis-ci.com/github/conda-forge/nvcomp-feedstock/jobs/618263183#L676-L677 ):

```
  ERROR (nvcomp,lib/libnvcomp.so): Needed DSO lib/libgomp.so.1 found in ['conda-forge/linux-aarch64::_openmp_mutex==4.5=2_gnu']
  ERROR (nvcomp,lib/libnvcomp.so): .. but ['conda-forge/linux-aarch64::_openmp_mutex==4.5=2_gnu'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

Edit: Reaching out offline

**Pull request merged**
